# Generated by Django 2.0 on 2018-03-31 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='KemuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成绩类型')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ParentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='家长名字')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cjcx2018.ClassRoomModel', verbose_name='所属班级')),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuwen', models.IntegerField(null=True, verbose_name='语文成绩')),
                ('shuxue', models.IntegerField(null=True, verbose_name='数学成绩')),
                ('yingyu', models.IntegerField(null=True, verbose_name='英语成绩')),
                ('wuli', models.IntegerField(null=True, verbose_name='物理成绩')),
                ('huaxue', models.IntegerField(null=True, verbose_name='化学成绩')),
                ('dili', models.IntegerField(null=True, verbose_name='地理成绩')),
                ('shengwu', models.IntegerField(null=True, verbose_name='生物成绩')),
                ('lishi', models.IntegerField(null=True, verbose_name='历史成绩')),
                ('zhengzhi', models.IntegerField(null=True, verbose_name='政治成绩')),
                ('tiyu', models.IntegerField(null=True, verbose_name='体育成绩')),
                ('qimo', models.IntegerField(null=True, verbose_name='期末成绩')),
                ('kemu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cjcx2018.KemuModel', verbose_name='成绩类别')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学生名字')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cjcx2018.ClassRoomModel', verbose_name='所属班级')),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cjcx2018.ParentsModel', verbose_name='父/母名称')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='老师名字')),
                ('subject', models.CharField(max_length=50, verbose_name='教学科目')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cjcx2018.StudentModel', verbose_name='所属学生'),
        ),
        migrations.AddField(
            model_name='classroommodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cjcx2018.TeacherModel', verbose_name='任课教师'),
        ),
    ]
