"""

Django settings for blog2018 project.



Generated by 'django-admin startproject' using Django 2.0.



For more information on this file, see

https://docs.djangoproject.com/en/2.0/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/2.0/ref/settings/

"""



import os



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))





# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'sffn@)wt%u0-#7h-x*($ss6%152j#vzunsxmk3^pgr15z^if_a'



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True



ALLOWED_HOSTS = []





# Application definition



INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'blog',

    'ckeditor',

    'ckeditor_uploader',
    'captcha',

   

]



MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]



ROOT_URLCONF = 'blog2018.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

                'django.template.context_processors.media' #将上传图片的media注册到这里，就可以使用

            ],

        },

    },

]



WSGI_APPLICATION = 'blog2018.wsgi.application'





# Database

# https://docs.djangoproject.com/en/2.0/ref/settings/#databases



DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.mysql',

        'NAME': 'tushu8',

        'USER': 'admin',

        'PASSWORD': 'wanwan',

        'HOST': '127.0.0.1',

        'PORT': '3306',

    }

}





# Password validation

# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]





# Internationalization

# https://docs.djangoproject.com/en/2.0/topics/i18n/



LANGUAGE_CODE = 'zh-hans'



TIME_ZONE = 'Asia/Shanghai'



USE_I18N = True



USE_L10N = True



USE_TZ = False





# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/2.0/howto/static-files/



STATIC_URL = '/static/'



MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/')     #设置静态文件路径为主目录下的media文件夹

MEDIA_URL = '/media/'#url映射

#富文本图片存放路径

CKEDITOR_UPLOAD_PATH = "article_images"

#富文本选项

CKEDITOR_CONFIGS = {

    'default': {

        'toolbar': (

			['div','Source','-','Save','NewPage','Preview','-','Templates'],

			['Cut','Copy','Paste','PasteText','PasteFromWord','-','Print','SpellChecker','Scayt'],

			['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],

			['Form','Checkbox','Radio','TextField','Textarea','Select','Button', 'ImageButton','HiddenField'],

			['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],

			['NumberedList','BulletedList','-','Outdent','Indent','Blockquote'],

			['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],

			['Link','Unlink','Anchor'],

			['Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak'],

			['Styles','Format','Font','FontSize'],

			['TextColor','BGColor'],

			['Maximize','ShowBlocks','-','About', 'pbckcode'],

		),

	}

}

