# Generated by Django 2.0 on 2018-04-17 10:51

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogwenzhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容')),
                ('release_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('amend_time', models.DateTimeField(auto_now=True, verbose_name='最后修改')),
                ('reads', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '博文发布',
                'verbose_name_plural': '博文发布',
                'ordering': ['-release_time'],
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='DianzanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wenzhang_id', models.IntegerField(verbose_name='被点文字ID')),
                ('zan_num', models.IntegerField(verbose_name='点赞数量')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞人ID')),
            ],
        ),
        migrations.CreateModel(
            name='Good_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名字')),
                ('gurl', models.CharField(max_length=100, verbose_name='跳转网址')),
                ('miaosu', models.CharField(max_length=200, verbose_name='描述说明')),
            ],
            options={
                'verbose_name': '友情链接管理',
                'verbose_name_plural': '友情链接管理',
            },
        ),
        migrations.CreateModel(
            name='Guanggaoimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='图片名字')),
                ('guanggao_img', models.ImageField(upload_to='index_img', verbose_name='上传图片')),
            ],
            options={
                'verbose_name': '广告图管理',
                'verbose_name_plural': '广告图管理',
            },
        ),
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='上传图片')),
                ('name', models.CharField(max_length=20, verbose_name='图片名字')),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '图片上传',
                'verbose_name_plural': '图片上传',
            },
        ),
        migrations.CreateModel(
            name='Lunbotu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='图片名字')),
                ('index_img', models.ImageField(upload_to='index_img', verbose_name='上传图片')),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '轮播图管理',
                'verbose_name_plural': '轮播图管理',
            },
        ),
        migrations.CreateModel(
            name='Pinlun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('author', models.CharField(max_length=50, verbose_name='评论人')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('email', models.CharField(max_length=50)),
                ('parent_pinlun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pp_pinlun', to='blog.Pinlun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='评论关联')),
                ('wenzhang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blogwenzhang', verbose_name='评论关联')),
            ],
            options={
                'verbose_name': '评论管理',
                'verbose_name_plural': '评论管理',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='置顶标题')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '置顶消息',
                'verbose_name_plural': '置顶消息',
            },
        ),
        migrations.CreateModel(
            name='User_EX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='static/avatar/moren.jpg', upload_to='static/avatar')),
                ('bj', models.CharField(default='blog_2018', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户头像管理',
                'verbose_name_plural': '用户头像管理',
            },
        ),
        migrations.AddField(
            model_name='blogwenzhang',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Classify', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='blogwenzhang',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.IMG', verbose_name='图片名字'),
        ),
    ]
