# Generated by Django 2.0 on 2018-03-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180321_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='上传图片')),
                ('name', models.CharField(max_length=20, verbose_name='图片名字')),
            ],
            options={
                'verbose_name': '图片上传',
                'verbose_name_plural': '图片上传',
            },
        ),
        migrations.AlterModelOptions(
            name='pinlun',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='blogwenzhang',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.IMG', verbose_name='图片名字'),
        ),
    ]
