# Generated by Django 2.0 on 2018-03-28 08:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_good_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunbotu',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogwenzhang',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容'),
        ),
    ]
