# Generated by Django 2.0 on 2018-04-13 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20180329_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='DianzanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wenzhang_id', models.IntegerField(verbose_name='被点文字ID')),
                ('zan_num', models.IntegerField(verbose_name='点赞数量')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞人ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pinlun',
            options={'ordering': ['-time'], 'verbose_name': '评论管理', 'verbose_name_plural': '评论管理'},
        ),
        migrations.AlterField(
            model_name='user_ex',
            name='avatar',
            field=models.ImageField(default='static/avatar/moren.jpg', upload_to='static/avatar'),
        ),
    ]
