# Generated by Django 2.0 on 2018-04-14 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180413_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinlun',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Pinlun'),
        ),
    ]
