# Generated by Django 2.0 on 2018-04-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_pinlun_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinlun',
            name='parent',
        ),
    ]
